name: Build and publish nuget packages

on:
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Install dependencies
      run: |
        dotnet tool install paket -g
        dotnet tool install fake-cli -g
        dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Fun.Routing/Fun.Routing.fsproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
